
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxiejogrelqxxkyhcwgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54aWVqb2dyZWxxeHhreWhjd2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjQ0OTcsImV4cCI6MjA2NjAwMDQ5N30.mSbM1tT3m3r6HKt5DoBBGpNiiiasH6QvNGjD2D68Z6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
